buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '[6.0,6.2)', changing: true
        classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'idea'
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

mixin {
    add sourceSets.main, "crust.mixins.refmap.json"
}


// The mod's version and id
version = "${mc_version}-${mod_version}"
archivesBaseName = 'crust'
group = "fathertoast.${archivesBaseName}"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: 'official', version: "${mc_version}"
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                crust {
                    source sourceSets.main
                    source sourceSets.test
                }
            }
        }

        client {
            property "mixin.debug.export", "true"
            property 'mixin.env.disableRefMap', 'true'

            arg "-mixin.config=crust.mixins.json"
        }

        server {
            property "mixin.debug.export", "true"
            property 'mixin.env.disableRefMap', 'true'

            arg "-mixin.config=crust.mixins.json"
        }

        data {
            args '--mod', 'crust', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name 'CurseMaven'
        url 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    // Just in case!
    flatDir {
        dir 'flat_deps'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"

    // Group ID must be present for flat dir repositories, but are effectively unused
    //runtimeOnly fg.deobf("blank:some_mod:version:descriptor")

    // Apocalypse & API
    // runtimeOnly fg.deobf("curse.maven:apocalypse-229199:${apocalypse_version}")
    // compileOnly fg.deobf("curse.maven:apocalypse_api-229199:${apocalypse_api_version}")
    runtimeOnly fg.deobf("blank:apocalypse:1.20.1-4.11.10:all")
    compileOnly fg.deobf("blank:apocalypse:1.20.1-4.11.10:api")

    // Other toasty mods // TODO Re-add later!
    // runtimeOnly fg.deobf("curse.maven:deadlyworld-60098:${dw_version}")
    // runtimeOnly fg.deobf("curse.maven:specialmobs-59968:${sm_version}")
    // runtimeOnly fg.deobf("curse.maven:natural-absorption-224296:${na_version}")
    // runtimeOnly fg.deobf("curse.maven:special-ai-224301:${sai_version}")
    // runtimeOnly fg.deobf("curse.maven:swiftdeath-1395967:${swdeath_version}")
    // runtimeOnly fg.deobf("curse.maven:tomfoolery-846404:${tom_version}")
    // runtimeOnly fg.deobf("curse.maven:magicalrelics-1056145:${mr_version}")

    // Curios
    runtimeOnly fg.deobf("curse.maven:curios-309927:${curios_version}")

    // Tinker's Construct
    runtimeOnly fg.deobf("curse.maven:tc-74072:${tc_version}")
    runtimeOnly fg.deobf("curse.maven:mantle-74924:${mantle_version}")

    // Jade
    runtimeOnly fg.deobf("curse.maven:jade-324717:${jade_version}")

    // MixinExtras
    // compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
    // implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixinextras_version}")) {
    //     jarJar.ranged(it, "[${mixinextras_version},)")
    // }

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "Crust",
                "Specification-Vendor"    : "FatherToast",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : "${mod_version}",
                "Implementation-Vendor"   : "FatherToast",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "crust.mixins.json"
        ])
    }
}

task srcJar(type: Jar) {
    archiveClassifier.set('src')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    // Include the entire mod (deobf) plus java files
    from sourceSets.main.output
    from sourceSets.main.allSource

    // Generate same jar manifest as main jar to include
    manifest {
        attributes([
                "Specification-Title"     : "Crust",
                "Specification-Vendor"    : "FatherToast",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : "${mod_version}",
                "Implementation-Vendor"   : "FatherToast",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "crust.mixins.json"
        ])
    }
}

task apiJar(type: Jar) {
    archiveClassifier.set('api')

    // Include only the api package
    include 'fathertoast/crust/api/**/*'

    from sourceSets.main.output
    from sourceSets.main.allSource
}

artifacts {
    archives srcJar
    archives apiJar
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact apiJar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}