# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#
# MAJOR, API, MINOR
mod_version=4.10.17
# Dependencies
mc_version=1.20.1
forge_version=47.4.0
#
# Misc toast mods
apocalypse_version=6499583
apocalypse_api_version=6499584
dw_version=7184183
sm_version=7557088
na_version=6512425
sai_version=7237330
#
# Jade
jade_version=6855440
#
# Tinker's Construct
tc_version=7449219
mantle_version=7563777
#
# Mixin Extras
mixinextras_version=0.5.3