# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#
# MAJOR, API, MINOR
mod_version=4.17.28
# Dependencies
mc_version=1.20.1
forge_version=47.4.10
#
# Misc toast mods
apocalypse_version=7236723
apocalypse_api_version=7236728
dw_version=8095770
sm_version=8014675
na_version=7572073
sai_version=7725043
swdeath_version=7719710
tom_version=8104573
mr_version=8087727
#
# Curios API
curios_version=6418456
#
# Jade
jade_version=6855440
#
# Tinker's Construct
tc_version=7449219
mantle_version=7563777
#
# Mixin Extras
# mixinextras_version=0.5.3