@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.common.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;