modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/FatherToast/Crust/issues/"

[[mods]]
logoFile = "banner.png"
authors = "Father Toast, Sarinsa"
credits = "The toasty people"
version = "${file.jarVersion}"
displayName = "Crust"
modId = "crust"
description = '''
A modding and testing toolkit with a few other minor utilities.


Download: https://www.curseforge.com/members/fathertoast/projects/

Source: https://github.com/FatherToast/

Discussion: https://discord.gg/GFTzTdX
'''

[[dependencies.crust]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crust]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crust]]
modId = "apocalypse"
mandatory = false
versionRange = "[1,)"
ordering = "BEFORE"
side = "BOTH"