@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;