@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.common.compat.naturalabsorption;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;