package fathertoast.crust.api.config.client.gui.screen;

import com.mojang.blaze3d.matrix.MatrixStack;
import fathertoast.crust.api.config.client.gui.widget.CrustConfigFieldList;
import fathertoast.crust.api.config.common.ConfigUtil;
import fathertoast.crust.api.config.common.file.CrustConfigFormat;
import fathertoast.crust.api.config.common.file.CrustConfigSpec;
import net.minecraft.client.gui.DialogTexts;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.TextFieldWidget;
import net.minecraft.client.gui.widget.button.Button;
import net.minecraft.client.util.InputMappings;
import net.minecraft.util.IReorderingProcessor;
import net.minecraft.util.Util;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.util.text.TranslationTextComponent;

import javax.annotation.Nullable;
import java.util.List;

/**
 * Screen that displays the contents of a single config file for the user to view and edit.
 *
 * @see fathertoast.crust.api.config.common.AbstractConfigFile
 * @see CrustConfigSpec
 */
public class CrustConfigFileScreen extends Screen {
    
    /** @return The spec's display name. */
    public static String getSpecName( CrustConfigSpec spec ) {
        String name = spec.getFile().getName();
        return ConfigUtil.properCase( decodeString( name.substring( 0, name.length() - CrustConfigFormat.FILE_EXT.length() ) ) );
    }
    
    /** @return The string made into something more readable. */
    public static String decodeString( String str ) {
        return ConfigUtil.camelCaseToLowerSpace( str.replace( '_', ' ' ).replace( ".", " > " ) );
    }
    
    
    /** The screen open under this one. */
    private final Screen LAST_SCREEN;
    
    /** The spec of the 'opened' config file. */
    private final CrustConfigSpec SPEC;
    
    /** The text to render below the title. */
    private final ITextComponent SUBTITLE;
    
    /** The list generated by the config spec to represent the file contents. */
    private CrustConfigFieldList fieldList;
    /** Tooltip to render this frame. */
    private List<IReorderingProcessor> tooltip;
    
    /** The "open file" or "discard changes" button. */
    private Button bottomLeftButton;
    /** The "done" or "save changes" button. */
    private Button bottomRightButton;
    
    /** The currently focused text box, if any. */
    private TextFieldWidget focusedTextBox;
    
    /** Creates a new config file screen. */
    public CrustConfigFileScreen( Screen parent, CrustConfigSpec spec ) {
        super( new TranslationTextComponent( "menu.crust.config.file.title",
                CrustConfigSelectScreen.getModName( spec.MANAGER.MOD_ID ), getSpecName( spec ) ) );
        LAST_SCREEN = parent;
        SPEC = spec;
        SUBTITLE = new TranslationTextComponent( "menu.crust.config.file.subtitle",
                ConfigUtil.toRelativePath( spec.getFile() ) );
    }
    
    /** Sets the tooltip to render this tick. */
    public void setTooltip( @Nullable List<IReorderingProcessor> text ) { tooltip = text; }
    
    /** Closes this screen and reopens it to hard-refresh everything. */
    public void resetScreen() {
        if( minecraft != null ) minecraft.setScreen( new CrustConfigFileScreen( LAST_SCREEN, SPEC ) );
    }
    
    /** Called when the screen is destroyed. */
    @Override
    public void removed() {
        //TODO
        //minecraft.options.save();
    }
    
    /** Called to close the screen. */
    @Override
    public void onClose() { if( minecraft != null ) minecraft.setScreen( LAST_SCREEN ); }
    
    /** Called to setup the screen before displaying it. */
    @Override
    protected void init() {
        if( minecraft == null ) return;
        
        // Header content
        // Nothing to init
        
        // Primary screen content
        fieldList = new CrustConfigFieldList( this, minecraft, SPEC );
        children.add( fieldList );
        
        // Footer content
        addButton( bottomLeftButton = new Button( width / 2 - 155, height - 29,
                150, 20, new TranslationTextComponent( "menu.crust.config.open_folder" ),
                ( button ) -> {
                    if( fieldList.isChanged() ) resetScreen();
                    else Util.getPlatform().openFile( SPEC.getFile().getParentFile() );
                } ) );
        addButton( bottomRightButton = new Button( width / 2 - 155 + 160, height - 29,
                150, 20, DialogTexts.GUI_DONE,
                ( button ) -> {
                    if( fieldList.isChanged() ) {
                        fieldList.saveChanges();
                        resetScreen();
                    }
                    else minecraft.setScreen( LAST_SCREEN );
                } ) );
    }
    
    public void updateFooterButtonText() {
        if( fieldList.isChanged() ) {
            bottomLeftButton.setMessage( new TranslationTextComponent( "menu.crust.config.discard_changes" )
                    .withStyle( TextFormatting.RED ) );
            bottomRightButton.setMessage( new TranslationTextComponent( "menu.crust.config.save_changes" )
                    .withStyle( TextFormatting.GREEN ) );
        }
        else {
            bottomLeftButton.setMessage( new TranslationTextComponent( "menu.crust.config.open_folder" ) );
            bottomRightButton.setMessage( DialogTexts.GUI_DONE );
        }
    }
    
    /**
     * Called when a mouse button is clicked.
     *
     * @param mouseKey The mouse key that was clicked (see {@link InputMappings.Type#MOUSE}).
     * @return True if the event has been handled.
     */
    @Override
    public boolean mouseClicked( double x, double y, int mouseKey ) {
        if( focusedTextBox != null ) {
            focusedTextBox.setFocus( false );
            focusedTextBox = null;
        }
        //TODO handle field edit popups
        //if( selectedKey != null ) {
        //    options.setKey( selectedKey, InputMappings.Type.MOUSE.getOrCreate( mouseKey ) );
        //    selectedKey = null;
        //    KeyBinding.resetMapping();
        //    return true;
        //}
        return super.mouseClicked( x, y, mouseKey );
    }
    
    /** Called to set the currently focused text box. */
    public void setFocusedTextBox( TextFieldWidget textBox ) { focusedTextBox = textBox; }
    
    /**
     * Called when a keyboard key is pressed.
     *
     * @param key      The keyboard key that was pressed (see {@link InputMappings.Type#KEYSYM}).
     * @param scancode The system-specific scancode of the key (see {@link InputMappings.Type#SCANCODE}).
     * @param mods     Bitfield describing which modifier keys were held down.
     * @return True if the event has been handled.
     * @see org.lwjgl.glfw.GLFWKeyCallbackI#invoke(long, int, int, int, int)
     */
    @Override
    public boolean keyPressed( int key, int scancode, int mods ) {
        //TODO handle field edit popups
        //if( selectedKey != null ) {
        //    if( key == 256 ) {
        //        selectedKey.setKeyModifierAndCode( net.minecraftforge.client.settings.KeyModifier.getActiveModifier(), InputMappings.UNKNOWN );
        //        options.setKey( selectedKey, InputMappings.UNKNOWN );
        //    }
        //    else {
        //        selectedKey.setKeyModifierAndCode( net.minecraftforge.client.settings.KeyModifier.getActiveModifier(), InputMappings.getKey( key, scancode ) );
        //        options.setKey( selectedKey, InputMappings.getKey( key, scancode ) );
        //    }
        //
        //    if( !net.minecraftforge.client.settings.KeyModifier.isKeyCodeModifier( selectedKey.getKey() ) )
        //        selectedKey = null;
        //    lastKeySelection = Util.getMillis();
        //    KeyBinding.resetMapping();
        //    return true;
        //}
        return super.keyPressed( key, scancode, mods );
    }
    
    /** Called each tick to update animations. */
    @Override
    public void tick() {
        if( focusedTextBox != null ) focusedTextBox.tick();
    }
    
    /** Called to render the screen. */
    @Override
    public void render( MatrixStack matrixStack, int mouseX, int mouseY, float partialTicks ) {
        renderBackground( matrixStack );
        
        setTooltip( null );
        fieldList.render( matrixStack, mouseX, mouseY, partialTicks );
        
        drawCenteredString( matrixStack, font, SUBTITLE, width / 2,
                24, 0x777777 );
        drawCenteredString( matrixStack, font, title, width / 2,
                8, 0xFFFFFF );
        
        super.render( matrixStack, mouseX, mouseY, partialTicks );
        
        if( tooltip != null ) {
            renderTooltip( matrixStack, tooltip, mouseX, mouseY );
        }
    }
}