package fathertoast.crust.client.screen.widget.entry;

import fathertoast.crust.api.config.client.gui.widget.entry.ConfigFieldGuiEntry;
import fathertoast.crust.api.config.client.gui.widget.field.ITooltipWidget;
import fathertoast.crust.api.config.client.gui.widget.field.ResetButton;
import fathertoast.crust.api.config.client.gui.widget.provider.IConfigFieldWidgetProvider;
import fathertoast.crust.api.config.common.field.IConfigField;
import fathertoast.crust.api.config.common.field.RestartNote;
import fathertoast.crust.api.config.common.file.TomlHelper;
import fathertoast.crust.client.screen.widget.CrustConfigFieldList;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.Tooltip;
import net.minecraft.client.gui.components.events.GuiEventListener;
import net.minecraft.network.chat.Component;
import net.minecraft.util.FormattedCharSequence;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents one field widget display entry in a {@link CrustConfigFieldList}.
 * These contain all functional components for fields in the in-game editor.
 * <p>
 * The field-specific contents of this entry are generated by the field's {@link IConfigFieldWidgetProvider}.
 */
public class FieldGuiEntry<T> extends ConfigFieldGuiEntry<T> {
    
    public final CrustConfigFieldList PARENT;
    
    private final List<FormattedCharSequence> NAME;
    private final List<FormattedCharSequence> TOOLTIP;
    
    private final Button RESET_BUTTON;
    private final List<OffsetWidget> RENDER_COMPONENTS = new ArrayList<>();
    
    public FieldGuiEntry( CrustConfigFieldList parent, IConfigField<T> field, String name,
                          @Nullable RestartNote restartNote, List<String> addedComment,
                          boolean remote, boolean editable ) {
        super( field, name, remote, editable );
        PARENT = parent;
        
        NAME = client().font.split( Component.literal( name ),
                CrustConfigFieldList.MAX_WIDTH - 2 - IConfigFieldWidgetProvider.VALUE_WIDTH - CrustConfigFieldList.RESET_BUTTON_WIDTH );
        TOOLTIP = new ArrayList<>();
        buildTooltip( TOOLTIP_WIDTH, restartNote, addedComment );
        if( TOOLTIP.size() > 20 ) { // Just brute force it a little
            TOOLTIP.clear();
            buildTooltip( (int) (TOOLTIP_WIDTH * 1.5), restartNote, addedComment );
            if( TOOLTIP.size() > 20 ) {
                TOOLTIP.clear();
                buildTooltip( TOOLTIP_WIDTH * 2, restartNote, addedComment );
            }
        }
        
        RESET_BUTTON = new ResetButton( 0, 0, // Position gets set when populated
                button -> {
                    updateValue( getField().getDefaultValue() );
                    populateComponents();
                } );
        RESET_BUTTON.active = isEditable() && !TomlHelper.equals( getField().getDefaultValue(), getValue() );
        populateComponents();
    }
    
    /** Builds or rebuilds all components in this list entry. */
    private void populateComponents() {
        COMPONENTS.clear();
        RENDER_COMPONENTS.clear();
        
        RESET_BUTTON.setX( IConfigFieldWidgetProvider.VALUE_WIDTH + 1 );
        RESET_BUTTON.setY( 0 );
        COMPONENTS.add( RESET_BUTTON );
        getField().getWidgetProvider().apply( COMPONENTS, this, getValue() );
        for( AbstractWidget component : COMPONENTS ) RENDER_COMPONENTS.add( new OffsetWidget( component ) );
    }
    
    /** Call this to change the field's pending "new" value. */
    public void updateValue( T value ) {
        if( !isEditable() ) return;
        pendingValue = value;
        RESET_BUTTON.active = !TomlHelper.equals( getField().getDefaultValue(), value );
        changed = !TomlHelper.equals( getSavedValue(), value );
        PARENT.updateChangedState();
        ensureVisible();
    }
    
    /** Call this to delete the field's pending "new" value. */
    @Override
    public void clearValue() {
        if( !isEditable() ) return;
        pendingValue = getSavedValue();
        RESET_BUTTON.active = !TomlHelper.equals( getField().getDefaultValue(), getSavedValue() );
        changed = false;
        PARENT.updateChangedState();
        ensureVisible();
    }
    
    /** Opens a popup widget over the screen. Setting to null closes any open popup. */
    @Override
    public void setPopupWidget( @Nullable AbstractWidget popup ) { PARENT.PARENT.setPopupWidget( popup ); }
    
    /** Centers this list entry on-screen by scrolling the list up or down. */
    @Override
    public void centerScrollOn() { PARENT.centerScrollOn( this ); }
    
    /** Ensures this list entry is on-screen by scrolling the list up or down. */
    @Override
    public void ensureVisible() { PARENT.ensureVisible( this ); }
    
    /** @return The screen's width. in GUI pixels. */
    @Override
    public int getScreenWidth() { return PARENT.getWidth(); }
    
    /** @return The screen's height. in GUI pixels. */
    @Override
    public int getScreenHeight() { return PARENT.getHeight(); }
    
    /** @return The tooltip to render when the mouse is over this entry. Null if no tooltip should render. */
    @Override
    @Nullable
    public List<FormattedCharSequence> getTooltip( int mouseX, int mouseY ) {
        if( mouseX < PARENT.getRowRight() - IConfigFieldWidgetProvider.VALUE_WIDTH - CrustConfigFieldList.RESET_BUTTON_WIDTH - CrustConfigFieldList.SCROLL_WIDTH )
            return TOOLTIP;
        for( OffsetWidget component : RENDER_COMPONENTS ) {
            if( component.WIDGET.isHovered() ) {
                if( component.WIDGET instanceof ITooltipWidget widget ) return widget.getTooltip( mouseX, mouseY );
                Tooltip tooltip = component.WIDGET.getTooltip();
                return tooltip == null ? null : tooltip.toCharSequence( Minecraft.getInstance() );
            }
        }
        return null;
    }
    
    @Override
    public void setFocused( @Nullable GuiEventListener component ) {
        if( component instanceof EditBox editBox ) PARENT.PARENT.setFocusedTextBox( editBox );
        super.setFocused( component );
    }
    
    /** Renders this list entry. */
    @Override
    public void render( GuiGraphics graphics, int index, int rowTop, int rowLeft, int rowWidth, int rowHeight,
                        int mouseX, int mouseY, boolean mouseOver, float partialTicks ) {
        int color = isChanged() ? 0x55FFFF : 0xFFFFFF;
        if( NAME.size() == 1 ) {
            graphics.drawString( client().font, NAME.get( 0 ),
                    rowLeft, rowTop + 6, color );
        }
        else if( NAME.size() >= 2 ) {
            graphics.drawString( client().font, NAME.get( NAME.size() - 2 ),
                    rowLeft, rowTop + 1, color );
            graphics.drawString( client().font, NAME.get( NAME.size() - 1 ),
                    rowLeft, rowTop + 10, color );
        }
        
        for( OffsetWidget component : RENDER_COMPONENTS ) {
            component.WIDGET.setX( component.X_OFFSET + rowLeft + CrustConfigFieldList.MAX_WIDTH - IConfigFieldWidgetProvider.VALUE_WIDTH - CrustConfigFieldList.RESET_BUTTON_WIDTH );
            component.WIDGET.setY( component.Y_OFFSET + rowTop );
            component.WIDGET.render( graphics, mouseX, mouseY, partialTicks );
        }
    }
    
    /** Builds this field entry's tooltip. */
    private void buildTooltip( int width, @Nullable RestartNote restartNote, List<String> addedComment ) {
        split( TOOLTIP, Component.literal( getField().getKey() )
                .withStyle( ChatFormatting.YELLOW ), width );
        if( getField().getComment() != null && !getField().getComment().isEmpty() ) {
            for( String line : getField().getComment() ) {
                split( TOOLTIP, Component.literal( line ), width );
            }
        }
        if( restartNote != null ) {
            split( TOOLTIP, Component.literal( restartNote.COMMENT )
                    .withStyle( ChatFormatting.RED ), width );
        }
        if( !addedComment.isEmpty() ) {
            final int maxChars = 150;
            int charCount = 0;
            
            for( String line : addedComment ) {
                charCount += line.length();
                
                // Prevent large tooltips from being
                // obnoxious and taking up the whole screen.
                if( charCount > maxChars ) {
                    int diff = charCount - maxChars;
                    line = line.substring( 0, line.length() - diff );
                    line = line + "...";
                    
                    split( TOOLTIP, Component.literal( line )
                            .withStyle( ChatFormatting.GRAY ), width );
                    break;
                }
                else {
                    split( TOOLTIP, Component.literal( line )
                            .withStyle( ChatFormatting.GRAY ), width );
                }
            }
        }
    }
    
    
    /**
     * Simple wrapper used to save the offsets of provided field gui components so
     * that they can be maintained as the component is moved/scrolled around on screen.
     */
    private static class OffsetWidget {
        
        final AbstractWidget WIDGET;
        final int X_OFFSET;
        final int Y_OFFSET;
        
        OffsetWidget( AbstractWidget widget ) {
            WIDGET = widget;
            X_OFFSET = widget.getX();
            Y_OFFSET = widget.getY();
        }
    }
}