@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package fathertoast.crust.api.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;