package fathertoast.crust.api.config.client.gui.widget.entry;

import fathertoast.crust.api.config.client.gui.widget.field.searchbar.Searchbar;
import fathertoast.crust.api.config.client.gui.widget.provider.IConfigFieldWidgetProvider;
import fathertoast.crust.api.config.common.field.IConfigField;
import fathertoast.crust.api.config.common.file.action.ICrustConfigGuiSpec;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.narration.NarratableEntry;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents one field widget display entry in a {@link ICrustConfigGuiSpec}.
 * These contain all functional components for fields in the in-game editor.
 * <p>
 * The field-specific contents of this entry are generated by the field's {@link IConfigFieldWidgetProvider}.
 */
public abstract class ConfigFieldGuiEntry<T> extends ConfigGuiEntry {
    
    protected final List<AbstractWidget> COMPONENTS = new ArrayList<>();
    
    private final String LOOKUP_NAME;
    private final boolean REMOTE;
    private final boolean EDITABLE;
    
    private final IConfigField<T> FIELD;
    private final T CURRENT_VALUE;
    
    protected T pendingValue;
    protected boolean changed;
    
    public ConfigFieldGuiEntry( IConfigField<T> field, String name, boolean remote, boolean editable ) {
        FIELD = field;
        LOOKUP_NAME = name;
        REMOTE = remote;
        EDITABLE = editable;
        CURRENT_VALUE = pendingValue = remote ? field.getRemoteValue() : field.getLocalValue();
    }
    
    /** @return The field represented by this field entry. */
    public IConfigField<T> getField() { return FIELD; }
    
    /** @return The field's current "saved" value. */
    public T getSavedValue() { return CURRENT_VALUE; }
    
    /** @return The field's pending "new" value. */
    public T getValue() { return pendingValue; }
    
    /** @return True if this field entry believes its pending value is different from the real field's value. */
    public boolean isChanged() { return changed; }
    
    /** @return True if this field entry belongs to a non-local server config. */
    public boolean isRemote() { return REMOTE; }
    
    /** @return True if the player has permission to edit this field entry. */
    public boolean isEditable() { return EDITABLE; }
    
    /** @return An identifying String to be looked up by a {@link Searchbar} */
    @Override // ISearchable
    @Nullable
    public String getLookupName() { return LOOKUP_NAME; }
    
    /**
     * When local, pushes the pending value to the underlying local config file, to prepare to save the config to disk.
     * <p>
     * When remote, pushes the pending value to the field's remote value, to prepare to send a config edit request.
     */
    public void pushValue() {
        if( REMOTE ) FIELD.setRemoteValue( getValue() );
        else FIELD.getSpec().getNightConfig().set( FIELD.getKey(), getValue() );
    }
    
    /** Call this to change the field's pending "new" value based on a string input. */
    public void updateInput( String text ) { updateValue( FIELD.parse( text ) ); }
    
    /** Call this to change the field's pending "new" value based on a string list input. */
    public void updateInput( List<String> text ) { updateValue( FIELD.parse( text ) ); }
    
    /** Call this to change the field's pending "new" value. */
    public abstract void updateValue( T value );
    
    /** Call this to delete the field's pending "new" value. */
    public abstract void clearValue();
    
    /** Opens a popup widget over the screen. Setting to null closes any open popup. */
    public abstract void setPopupWidget( @Nullable AbstractWidget popup );
    
    /** Centers this list entry on-screen by scrolling the list up or down. */
    public abstract void centerScrollOn();
    
    /** Ensures this list entry is on-screen by scrolling the list up or down. */
    public abstract void ensureVisible();
    
    /** @return The screen's width. in GUI pixels. */
    public abstract int getScreenWidth();
    
    /** @return The screen's height. in GUI pixels. */
    public abstract int getScreenHeight();
    
    @Override
    public List<AbstractWidget> children() { return COMPONENTS; }
    
    /** @return Narrations for this entry. */
    @Override
    public List<? extends NarratableEntry> narratables() { return children(); }
}