@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.common.core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;