@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.common.potion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;