@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.client.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;