@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.crust.common.mode;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;