package fathertoast.crust.api.util.shape;

import fathertoast.crust.api.lib.CrustMath;
import net.minecraft.nbt.CompoundTag;

/**
 * Represents a shape with a position/offset and color.
 */
public abstract class AbstractColoredShape extends AbstractShape {
    
    /** This shape's alpha (0.0 - 1.0). */
    private float alpha = 1.0F;
    /** This shape's red (0.0 - 1.0). */
    private float red = 1.0F;
    /** This shape's green (0.0 - 1.0). */
    private float green = 1.0F;
    /** This shape's blue (0.0 - 1.0). */
    private float blue = 1.0F;
    
    /** @return The alpha (opacity) of this shape (0.0 - 1.0). */
    public float alpha() { return alpha; }
    
    /** @return The red portion of this shape's color (0.0 - 1.0). */
    public float red() { return red; }
    
    /** @return The green portion of this shape's color (0.0 - 1.0). */
    public float green() { return green; }
    
    /** @return The blue portion of this shape's color (0.0 - 1.0). */
    public float blue() { return blue; }
    
    /** Sets the alpha (opacity) of this shape (0.0 - 1.0) and returns it. */
    public AbstractColoredShape withAlpha( float a ) {
        alpha = a;
        return this;
    }
    
    /** Sets the red portion of this shape's color (0.0 - 1.0) and returns it. */
    public AbstractColoredShape withRed( float r ) {
        red = r;
        return this;
    }
    
    /** Sets the green portion of this shape's color (0.0 - 1.0) and returns it. */
    public AbstractColoredShape withGreen( float g ) {
        green = g;
        return this;
    }
    
    /** Sets the blue portion of this shape's color (0.0 - 1.0) and returns it. */
    public AbstractColoredShape withBlue( float b ) {
        blue = b;
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. The shape will be fully opaque. */
    public AbstractColoredShape withColor( float r, float g, float b ) {
        return withColor( 1.0F, r, g, b );
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. */
    public AbstractColoredShape withColor( float a, float r, float g, float b ) {
        alpha = a;
        red = r;
        green = g;
        blue = b;
        return this;
    }
    
    /**
     * Sets the color and alpha (opacity) of this shape and returns it.
     * Accepts both RGB and ARGB color ints - as a side effect, this does not allow setting alpha to 0.
     */
    public AbstractColoredShape withColor( int color ) {
        return CrustMath.getAlphaBits( color ) == 0 ? withRGB( color ) : withARGB( color );
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. The shape will be fully opaque. */
    public AbstractColoredShape withRGB( int rgb ) { return withARGB( 0xFF000000 | rgb ); }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. */
    public AbstractColoredShape withARGB( int argb ) {
        return withColor( CrustMath.getAlpha( argb ), CrustMath.getRed( argb ),
                CrustMath.getGreen( argb ), CrustMath.getBlue( argb ) );
    }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        super.serialize( shapeTag );
        shapeTag.putInt( "clr", CrustMath.toARGB( alpha, red, green, blue ) );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        super.deserialize( shapeTag );
        withARGB( shapeTag.getInt( "clr" ) );
    }
}