package fathertoast.crust.api.util.shape;

import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;

public abstract class AbstractDirectionShape extends AbstractColoredShape {
    
    private Direction direction = Direction.UP;
    
    /** @return The direction this shape faces. */
    public Direction direction() { return direction; }
    
    /** Sets the direction this shape faces and returns it. */
    public AbstractDirectionShape withDir( Direction dir ) {
        direction = dir;
        return this;
    }
    
    /** Sets the axis this shape faces and returns it. */
    public AbstractDirectionShape withAxis( Direction.Axis axis ) {
        return withDir( Direction.get( Direction.AxisDirection.POSITIVE, axis ) );
    }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        super.serialize( shapeTag );
        shapeTag.putByte( "dir", (byte) direction.get3DDataValue() );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        super.deserialize( shapeTag );
        direction = Direction.from3DDataValue( shapeTag.getByte( "dir" ) );
    }
}