package fathertoast.crust.api.util.shape;

import fathertoast.crust.api.util.IDebugShape;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.phys.Vec3;

/**
 * Represents a shape with a position/offset.
 * <p>
 * This is used as the base for all built-in shapes, since including a position
 * enables rendering standalone shapes and is still handy as an offset for
 * positional shapes.
 */
public abstract class AbstractShape implements IDebugShape {
    
    /** This shape's position/offset. */
    private Vec3 position = Vec3.ZERO;
    
    /** @return This shape's position. */
    public Vec3 pos() { return position; }
    
    /** Sets this shape's position and returns it. */
    public AbstractShape withPos( double x, double y, double z ) {
        return withPos( new Vec3( x, y, z ) );
    }
    
    /** Sets this shape's position and returns it. */
    public AbstractShape withPos( Vec3 pos ) {
        position = pos;
        return this;
    }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        shapeTag.putDouble( "x", position.x() );
        shapeTag.putDouble( "y", position.y() );
        shapeTag.putDouble( "z", position.z() );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        position = new Vec3(
                shapeTag.getDouble( "x" ),
                shapeTag.getDouble( "y" ),
                shapeTag.getDouble( "z" ) );
    }
}