package fathertoast.crust.api.util.shape;

import fathertoast.crust.api.ICrustApi;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

public class CylinderShape extends AbstractDirectionShape {
    
    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath( ICrustApi.MOD_ID, "cylinder" );
    
    private float radius;
    private float height;
    
    public CylinderShape() { }
    
    public CylinderShape( float r, float h ) { withSize( r, h ); }
    
    public CylinderShape( Direction dir, float r, float h ) { withDir( dir ).withSize( r, h ); }
    
    public CylinderShape( Direction.Axis axis, float r, float h ) { withAxis( axis ).withSize( r, h ); }
    
    /**
     * @return The id that this shape is registered to. Generally, each non-abstract
     * shape class should override this method and return its own unique id.
     */
    @Override
    public ResourceLocation getId() { return ID; }
    
    /** @return The radius of this shape. */
    public float radius() { return radius; }
    
    /** Sets the radius of this shape and returns it. */
    public CylinderShape withRadius( float r ) {
        radius = r;
        return this;
    }
    
    /** @return The height of this shape. */
    public float height() { return height; }
    
    /** Sets the height of this shape and returns it. */
    public CylinderShape withHeight( float h ) {
        height = h;
        return this;
    }
    
    /** Sets the radius and height of this shape and returns it. */
    public CylinderShape withSize( float r, float h ) { return withRadius( r ).withHeight( h ); }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        super.serialize( shapeTag );
        shapeTag.putFloat( "r", radius );
        shapeTag.putFloat( "h", height );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        super.deserialize( shapeTag );
        radius = shapeTag.getFloat( "r" );
        height = shapeTag.getFloat( "h" );
    }
    
    
    // ---- Builder-Type Methods ---- //
    
    /** Sets this shape's position and returns it. */
    @Override
    public CylinderShape withPos( double x, double y, double z ) {
        super.withPos( x, y, z );
        return this;
    }
    
    /** Sets this shape's position and returns it. */
    @Override
    public CylinderShape withPos( Vec3 pos ) {
        super.withPos( pos );
        return this;
    }
    
    /** Sets the alpha (opacity) of this shape (0 to 1) and returns it. */
    @Override
    public CylinderShape withAlpha( float a ) {
        super.withAlpha( a );
        return this;
    }
    
    /** Sets the red portion of this shape's color (0 to 1) and returns it. */
    @Override
    public CylinderShape withRed( float r ) {
        super.withRed( r );
        return this;
    }
    
    /** Sets the green portion of this shape's color (0 to 1) and returns it. */
    @Override
    public CylinderShape withGreen( float g ) {
        super.withGreen( g );
        return this;
    }
    
    /** Sets the blue portion of this shape's color (0 to 1) and returns it. */
    @Override
    public CylinderShape withBlue( float b ) {
        super.withBlue( b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. The shape will be fully opaque. */
    @Override
    public CylinderShape withColor( float r, float g, float b ) {
        super.withColor( r, g, b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. */
    @Override
    public CylinderShape withColor( float a, float r, float g, float b ) {
        super.withColor( a, r, g, b );
        return this;
    }
    
    /**
     * Sets the color and alpha (opacity) of this shape and returns it.
     * Accepts both RGB and ARGB color ints - as a side effect, this does not allow setting alpha to 0.
     */
    @Override
    public CylinderShape withColor( int color ) {
        super.withColor( color );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. The shape will be fully opaque. */
    @Override
    public CylinderShape withRGB( int rgb ) {
        super.withRGB( rgb );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. */
    @Override
    public CylinderShape withARGB( int argb ) {
        super.withARGB( argb );
        return this;
    }
    
    /** Sets the direction this shape faces and returns it. */
    @Override
    public CylinderShape withDir( Direction dir ) {
        super.withDir( dir );
        return this;
    }
    
    /** Sets the axis this shape faces and returns it. */
    @Override
    public CylinderShape withAxis( Direction.Axis axis ) {
        super.withAxis( axis );
        return this;
    }
}