package fathertoast.crust.api.util.shape;

import fathertoast.crust.api.ICrustApi;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

public class QuadShape extends AbstractDirectionShape {
    
    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath( ICrustApi.MOD_ID, "quad" );
    
    private float halfWidth;
    private float halfHeight;
    
    public QuadShape() { }
    
    public QuadShape( float w ) { withSize( w, w ); }
    
    public QuadShape( float w, float h ) { withSize( w, h ); }
    
    public QuadShape( Direction dir, float w ) { withDir( dir ).withSize( w, w ); }
    
    public QuadShape( Direction dir, float w, float h ) { withDir( dir ).withSize( w, h ); }
    
    public QuadShape( Direction.Axis axis, float w ) { withAxis( axis ).withSize( w, w ); }
    
    public QuadShape( Direction.Axis axis, float w, float h ) { withAxis( axis ).withSize( w, h ); }
    
    /**
     * @return The id that this shape is registered to. Generally, each non-abstract
     * shape class should override this method and return its own unique id.
     */
    @Override
    public ResourceLocation getId() { return ID; }
    
    /**
     * @return The width of this shape.
     * For y-axis quads, this is the x dimension. For x- and z-axis quads, this is the z or x dimension, respectively.
     */
    public float width() { return halfWidth * 2.0F; }
    
    /** @return Half the {@link #width()}, for convenience . */
    public float halfWidth() { return halfWidth; }
    
    /**
     * Sets the width of this shape and returns it.
     * For y-axis quads, this is the x dimension. For x- and z-axis quads, this is the z or x dimension, respectively.
     */
    public QuadShape withWidth( float w ) {
        halfWidth = w / 2.0F;
        return this;
    }
    
    /**
     * @return The height of this shape.
     * For y-axis quads, this is the z dimension. For x- and z-axis quads, this is the y dimension.
     */
    public float height() { return halfHeight * 2.0F; }
    
    /** @return Half the {@link #height()}, for convenience . */
    public float halfHeight() { return halfHeight; }
    
    /**
     * Sets the height of this shape and returns it.
     * For y-axis quads, this is the z dimension. For x- and z-axis quads, this is the y dimension.
     */
    public QuadShape withHeight( float h ) {
        halfHeight = h / 2.0F;
        return this;
    }
    
    /** Sets the size of this shape and returns it. */
    public QuadShape withSize( float w, float h ) { return withWidth( w ).withHeight( h ); }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        super.serialize( shapeTag );
        shapeTag.putFloat( "w", halfWidth );
        shapeTag.putFloat( "h", halfHeight );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        super.deserialize( shapeTag );
        halfWidth = shapeTag.getFloat( "w" );
        halfHeight = shapeTag.getFloat( "h" );
    }
    
    
    // ---- Builder-Type Methods ---- //
    
    /** Sets this shape's position and returns it. */
    @Override
    public QuadShape withPos( double x, double y, double z ) {
        super.withPos( x, y, z );
        return this;
    }
    
    /** Sets this shape's position and returns it. */
    @Override
    public QuadShape withPos( Vec3 pos ) {
        super.withPos( pos );
        return this;
    }
    
    /** Sets the alpha (opacity) of this shape (0 to 1) and returns it. */
    @Override
    public QuadShape withAlpha( float a ) {
        super.withAlpha( a );
        return this;
    }
    
    /** Sets the red portion of this shape's color (0 to 1) and returns it. */
    @Override
    public QuadShape withRed( float r ) {
        super.withRed( r );
        return this;
    }
    
    /** Sets the green portion of this shape's color (0 to 1) and returns it. */
    @Override
    public QuadShape withGreen( float g ) {
        super.withGreen( g );
        return this;
    }
    
    /** Sets the blue portion of this shape's color (0 to 1) and returns it. */
    @Override
    public QuadShape withBlue( float b ) {
        super.withBlue( b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. The shape will be fully opaque. */
    @Override
    public QuadShape withColor( float r, float g, float b ) {
        super.withColor( r, g, b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. */
    @Override
    public QuadShape withColor( float a, float r, float g, float b ) {
        super.withColor( a, r, g, b );
        return this;
    }
    
    /**
     * Sets the color and alpha (opacity) of this shape and returns it.
     * Accepts both RGB and ARGB color ints - as a side effect, this does not allow setting alpha to 0.
     */
    @Override
    public QuadShape withColor( int color ) {
        super.withColor( color );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. The shape will be fully opaque. */
    @Override
    public QuadShape withRGB( int rgb ) {
        super.withRGB( rgb );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. */
    @Override
    public QuadShape withARGB( int argb ) {
        super.withARGB( argb );
        return this;
    }
    
    /** Sets the direction this shape faces and returns it. */
    @Override
    public QuadShape withDir( Direction dir ) {
        super.withDir( dir );
        return this;
    }
    
    /** Sets the axis this shape faces and returns it. */
    @Override
    public QuadShape withAxis( Direction.Axis axis ) {
        super.withAxis( axis );
        return this;
    }
}