package fathertoast.crust.api.util.shape;

import fathertoast.crust.api.ICrustApi;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

public class SphereShape extends CircleShape {
    
    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath( ICrustApi.MOD_ID, "sphere" );
    
    public SphereShape() { }
    
    public SphereShape( float r ) { withRadius( r ); }
    
    public SphereShape( Direction dir, float r ) { withDir( dir ).withRadius( r ); }
    
    public SphereShape( Direction.Axis axis, float r ) { withAxis( axis ).withRadius( r ); }
    
    /**
     * @return The id that this shape is registered to. Generally, each non-abstract
     * shape class should override this method and return its own unique id.
     */
    @Override
    public ResourceLocation getId() { return ID; }
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    @Override
    public void serialize( CompoundTag shapeTag ) {
        super.serialize( shapeTag );
    }
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    @Override
    public void deserialize( CompoundTag shapeTag ) {
        super.deserialize( shapeTag );
    }
    
    
    // ---- Builder-Type Methods ---- //
    
    /** Sets this shape's position and returns it. */
    @Override
    public SphereShape withPos( double x, double y, double z ) {
        super.withPos( x, y, z );
        return this;
    }
    
    /** Sets this shape's position and returns it. */
    @Override
    public SphereShape withPos( Vec3 pos ) {
        super.withPos( pos );
        return this;
    }
    
    /** Sets the alpha (opacity) of this shape (0 to 1) and returns it. */
    @Override
    public SphereShape withAlpha( float a ) {
        super.withAlpha( a );
        return this;
    }
    
    /** Sets the red portion of this shape's color (0 to 1) and returns it. */
    @Override
    public SphereShape withRed( float r ) {
        super.withRed( r );
        return this;
    }
    
    /** Sets the green portion of this shape's color (0 to 1) and returns it. */
    @Override
    public SphereShape withGreen( float g ) {
        super.withGreen( g );
        return this;
    }
    
    /** Sets the blue portion of this shape's color (0 to 1) and returns it. */
    @Override
    public SphereShape withBlue( float b ) {
        super.withBlue( b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. The shape will be fully opaque. */
    @Override
    public SphereShape withColor( float r, float g, float b ) {
        super.withColor( r, g, b );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape (0.0 - 1.0) and returns it. */
    @Override
    public SphereShape withColor( float a, float r, float g, float b ) {
        super.withColor( a, r, g, b );
        return this;
    }
    
    /**
     * Sets the color and alpha (opacity) of this shape and returns it.
     * Accepts both RGB and ARGB color ints - as a side effect, this does not allow setting alpha to 0.
     */
    @Override
    public SphereShape withColor( int color ) {
        super.withColor( color );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. The shape will be fully opaque. */
    @Override
    public SphereShape withRGB( int rgb ) {
        super.withRGB( rgb );
        return this;
    }
    
    /** Sets the color and alpha (opacity) of this shape and returns it. */
    @Override
    public SphereShape withARGB( int argb ) {
        super.withARGB( argb );
        return this;
    }
    
    /** Sets the direction this shape faces and returns it. */
    @Override
    public SphereShape withDir( Direction dir ) {
        super.withDir( dir );
        return this;
    }
    
    /** Sets the axis this shape faces and returns it. */
    @Override
    public SphereShape withAxis( Direction.Axis axis ) {
        super.withAxis( axis );
        return this;
    }
    
    /** Sets the radius of this shape and returns it. */
    @Override
    public SphereShape withRadius( float r ) {
        super.withRadius( r );
        return this;
    }
}