package fathertoast.crust.api.util; // TODO move to util.shape in MC versions beyond 1.20.1

import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;

/**
 * Represents a shape that may be rendered in the world.
 * <br>
 * Must be registered with a factory and renderer on the client.
 */
public interface IDebugShape {
    /**
     * @return The id that this shape is registered to. Generally, each non-abstract
     * shape class should override this method and return its own unique id.
     */
    ResourceLocation getId();
    
    /** Writes this shape to nbt. Called to serialize this shape to send to clients. */
    default void serialize( CompoundTag shapeTag ) { } // TODO implement shape packets to enable sending to client like particles
    
    /**
     * Loads this shape from nbt. Called to deserialize data received from the
     * server after being generated by its registered factory.
     */
    default void deserialize( CompoundTag shapeTag ) { }
}