package fathertoast.crust.api.util;

import net.minecraft.util.RandomSource;
import net.minecraft.world.level.levelgen.LegacyRandomSource;
import net.minecraft.world.level.levelgen.PositionalRandomFactory;

import java.util.Random;

/**
 * A wrapper for Java's {@link Random} to allow passing it into methods
 * that call for Minecraft's {@link RandomSource}.
 */
public class JavaRandomSource implements RandomSource {
    
    public static JavaRandomSource arbitrary() { return of( new Random() ); }
    
    public static JavaRandomSource of( long seed ) { return of( new Random( seed ) ); }
    
    public static JavaRandomSource of( Random random ) { return new JavaRandomSource( random ); }
    
    
    private final Random random;
    
    private JavaRandomSource( Random r ) { random = r; }
    
    /** @return A new random number generator, with seed randomly generated by this one. */
    @Override
    public RandomSource fork() { return of( nextLong() ); }
    
    /** @return A positional random factory using Minecraft's random, rather than Java random. */
    @Override
    public PositionalRandomFactory forkPositional() {
        return new LegacyRandomSource.LegacyPositionalRandomFactory( nextLong() );
    }
    
    /** Sets the seed of this random number generator. */
    @Override
    public void setSeed( long seed ) { random.setSeed( seed ); }
    
    /** @return A random integer (of any possible int value) with uniform distribution. */
    @Override
    public int nextInt() { return random.nextInt(); }
    
    /**
     * @return A random integer between 0 (inclusive) and the bound (exclusive) with uniform distribution.
     * @throws IllegalArgumentException If the bound is not positive.
     */
    @Override
    public int nextInt( int bound ) { return random.nextInt( bound ); }
    
    /**
     * @return A random integer between the origin (inclusive) and bound (exclusive) with uniform distribution.
     * @throws IllegalArgumentException If the origin is greater than or equal to the bound.
     */
    @Override
    public int nextInt( int origin, int bound ) { return RandomSource.super.nextInt( origin, bound ); }
    
    /**
     * @return A random integer between the minimum and maximum (both inclusive) with uniform distribution.
     * @throws IllegalArgumentException If the minimum is greater than the maximum.
     */
    @Override
    public int nextIntBetweenInclusive( int min, int max ) { return RandomSource.super.nextIntBetweenInclusive( min, max ); }
    
    /** @return A random long with uniform distribution. Note: not enough resolution to return all possible long values. */
    @Override
    public long nextLong() { return random.nextLong(); }
    
    /** @return A random boolean; true and false have approximately equal chance of being returned. */
    @Override
    public boolean nextBoolean() { return random.nextBoolean(); }
    
    /** @return A random float between 0.0 (inclusive) and 1.0 (exclusive) with uniform distribution. */
    @Override
    public float nextFloat() { return random.nextFloat(); }
    
    /** @return A random double between 0.0 (inclusive) and 1.0 (exclusive) with uniform distribution. */
    @Override
    public double nextDouble() { return random.nextDouble(); }
    
    /**
     * @return A random double with the standard normal distribution; that is, a normal distribution with
     * mean of 0.0 and standard deviation of 1.0.<p>
     * Approximately 68% of values will be within ±1.0, 95% within ±2.0, and 99.7% within ±3.0.
     */
    @Override
    public double nextGaussian() { return random.nextGaussian(); }
    
    /**
     * @return A random double in the range of mean ± spread (both exclusive) with a triangular distribution;
     * values closer to mean are more likely to be generated than values closer to the min or max.
     */
    @Override
    public double triangle( double mean, double spread ) { return RandomSource.super.triangle( mean, spread ); }
    
    /** Burns a number of 32-bit rolls (nextInt()). Probably not useful in this context. */
    @Override
    public void consumeCount( int n ) { RandomSource.super.consumeCount( n ); }
}